Update documentation
nest/nest-extension-module pull request #24
Opened 2023-12-07 11:08 UTC by clinssen

- make the GitHub landing page readme more minimal; point to ReadTheDocs for full documentation
- merge "synapses in NEST" and "writing custom synapse models" pages
- remove abstruse ``build.sh`` script in favour of better installation instructions on RtD and contents moved to GitHub workflow file
- many small fixes in the documentation to make it consistent with current state of affairs

2023-12-07 14:00 UTC, jessica-mitchell requested changes

2023-12-14 15:57 UTC, pnbabu requested changes

2023-12-14 15:57 UTC, pnbabu commented on doc/synapse_models.rst
> +All delays are handled inside the neuron, as described above. This means that when a spike "passes through" the Connection object, the actual biological arrival time (time when spike occured at sende
```suggestion
All delays are handled inside the neuron, as described above. This means that when a spike "passes through" the ``Connection`` object, the actual biological arrival time (time when spike occurred at sender plus delay) of the spike may be up to max_delay (maximum delay) time units in the future. This means, in particular, that ``Connection`` objects cannot perform any computations that depend on the state of the neuron at the time of "biological" spike arrival; they can only use historic information.
```

2024-01-08 13:02 UTC, clinssen commented on doc/synapse_models.rst
> +The source node of a connection is implicitly stored by the position in the data structure that is used internally. These parameters are implemented in the StaticConnection synapse type, which can be
```suggestion
These parameters are implemented in the static_synapse model, which can be used as a base class for more advanced synapse types.

Note that the source node of a connection is implicitly stored by the position in the data structure that is used internally in the NEST kernel.
```

2024-01-08 13:03 UTC, clinssen commented on doc/synapse_models.rst
> +All delays are handled inside the neuron, as described above. This means that when a spike "passes through" the Connection object, the actual biological arrival time (time when spike occured at sende
```suggestion
All delays are handled inside the neuron, as described above. This means that when a spike "passes through" the Connection object, the actual biological arrival time (time when spike occured at sender plus delay) of the spike may be up to ``max_delay`` (maximum delay) time units in the future. This means, in particular, that Connection objects cannot perform any computations that depend on the state of the neuron at the time of "biological" spike arrival; they can only use historic information.
```

2024-01-08 13:04 UTC, clinssen commented on doc/synapse_models.rst
> +All delays are handled inside the neuron, as described above. This means that when a spike "passes through" the Connection object, the actual biological arrival time (time when spike occured at sende
merged with Jessica's suggestion

2024-01-08 13:04 UTC, clinssen commented on doc/synapse_models.rst
> +All delays are handled inside the neuron, as described above. This means that when a spike "passes through" the Connection object, the actual biological arrival time (time when spike occured at sende
Merged with Pooja's suggestion

2024-01-08 13:06 UTC, clinssen commented on doc/extension_modules.rst
>  Building MyModule
The class name is ``MyModule``, so I would say the distinction between caps/no caps is probably a meaningful one to retain.

2024-01-08 13:08 UTC, clinssen commented on doc/overview.rst
> +   NEST version only; in particular the git "master" branch on
I would like to keep this as a highlight in README.rst as it's quite important to note.

2024-01-08 13:30 UTC, clinssen commented on doc/overview.rst
> +Installation
removed from overview.rst.

2026-03-04 11:10 UTC, merged