Revised module suitable for new NESTExtensionModule interface
nest/nest-extension-module pull request #26
Opened 2024-02-12 17:11 UTC by heplesser

This is the first example (in draft state) of the new `NESTExtensionInterface` and `ModuleManager` approach to handling modules.

2024-02-13 08:06 UTC, heplesser commented
Even while the example module still needs a lot of polishing, this one should be reviewed and merged soon so we have one that works with the new NEST mechanism. Then we also need to think about versioning these modules, we need releases that fit the NEST releases.

2024-03-12 10:07 UTC, terhorstd requested changes
Good suggestion to switch to `mynest` namespace.
Some small points

2024-04-04 09:19 UTC, pnbabu commented on src/mymodule.cpp
> +  //nest::kernel().connection_manager.register_conn_builder< mynest::StepPatternBuilder >( "step_pattern" );
@heplesser Could you remove these comments as they can be unloaded now?

2024-04-05 11:58 UTC, heplesser commented on src/mymodule.cpp
> +  //nest::kernel().connection_manager.register_conn_builder< mynest::StepPatternBuilder >( "step_pattern" );
Done.

2024-04-05 13:05 UTC, pnbabu requested changes
I have one minor comment. 

Also, what did we decide on the TODOs in the CMakeLists.txt file? Shall we remove them now and create an issue to address it later?

2024-04-15 12:49 UTC, pnbabu commented
@heplesser ping!

2024-04-15 13:45 UTC, heplesser commented on src/mymodule.cpp
> +  // Next three not registered for now, since they do not unload on ResetKernel
@pnbabu Done.

2024-04-15 13:56 UTC, pnbabu commented on CMakeLists.txt
> +# generation needs review
@heplesser what did we decide on these TODOs? Shall we remove them now and fix in a later PR?

2024-04-24 06:48 UTC, heplesser commented on CMakeLists.txt
> +# CPack stuff. Required for target `dist`. -- TODO: Do we really need this?
Removed, see #27 for follow-up.

2024-04-24 06:48 UTC, heplesser commented on CMakeLists.txt
> +# add make dist target -- TODO: Do we want this?
TODO removed, see #28 for follow-up.

2024-04-24 06:50 UTC, heplesser commented on CMakeLists.txt
> +# check the user link libraries whether installed or not -- TODO: need this?
TODO removed, see #29 for follow-up.

2024-04-24 06:51 UTC, heplesser commented on CMakeLists.txt
> +# generation needs review
TODO removed, see #26 for follow-up.

2024-04-24 06:52 UTC, heplesser commented
@terhorstd @pnbabu I have now addressed your comments, I hope to your content.

2024-04-24 08:23 UTC, heplesser commented on CMakeLists.txt
> +# generation needs review
I removed the comment, covered by #26

2024-04-24 09:24 UTC, pnbabu reviewed
It looks good to me overall. I am fine with merging this after fixing the failing build on macOS.

2024-04-24 09:42 UTC, heplesser commented
> It looks good to me overall. I am fine with merging this after fixing the failing build on macOS.

I have now hiked the Python version to 3.12, so building should work again on macOS.

2024-04-24 09:44 UTC, heplesser commented
But now the Linux build failed with what looks like a problem not related to our code. Strangely, I do not find a re-run button for actions in this repo. Let's see how it goes with the macOS build.

2024-04-24 09:47 UTC, pnbabu commented
> But now the Linux build failed with what looks like a problem not related to our code. Strangely, I do not find a re-run button for actions in this repo. Let's see how it goes with the macOS build.

Perhaps it's the access issue? I could see the button and the job is running again now.

2024-04-24 19:40 UTC, pnbabu approved these changes
The CI is green!

2024-04-26 10:53 UTC, terhorstd approved these changes
At some point we will have a discussion about the Python versions again, but that's a different story and will be told in another PR.
Thanks for all the effort!

2024-04-26 10:53 UTC, merged